## 文件服务
#minio:
#  enabled: true
#  endpoint: 127.0.0.1
#  port: 11000
#  accessKey: admin
#  secretKey: 12345678
#  secure: false
#  bucketDefaultName: file
#<dependency>
#    <groupId>com.squareup.okhttp3</groupId>
#    <artifactId>okhttp</artifactId>
#    <version>4.8.1</version>
#</dependency> 