## 文件服务
#amazons3:
#  enabled: true
#  endpoint: http://127.0.0.1:11000
#  accessKey: admin
#  secretKey: 12345678
#  secure: false
#  bucketName: amazon-s3
#  extend:
#    expriy:
#      # 文件过期天数
#      expriyDay: 7
#      # 文件过期策略初始化
#      expriyInitRule: true